services: 
  authservice:
    build: .
    ports:
      - "3000:3000"
    container_name: auth_service
    volumes:
      - ./:/app
      - /app/node_modules  
    command: npm run dev
    env_file:
      - .env
    depends_on:
      - postgres
      - mailhog
      - redis
  
  mailhog:
    image: mailhog/mailhog
    container_name: auth_mailhog
    platform: linux/amd64
    ports:
      - "1025:1025" 
      - "8025:8025"
  postgres:
    image: postgres:16
    container_name: auth_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    container_name: auth_redis
    ports:
      - "6379:6379"

volumes:
  pgdata: