services: 
  authService:
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    command: npm run dev
    env_file:
      - .env
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: