services:
  postgres_test:
    image: postgres:16-alpine
    container_name: auth_postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb_test
    ports:
      - "5434:5432"
    command: ["postgres", "-c", "fsync=off"]